// <auto-generated />
namespace MeetingsWebAPI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class personmeet : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(personmeet));
        
        string IMigrationMetadata.Id
        {
            get { return "201707172244112_personmeet"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
